// ===== MANUAL CONTENT (ENGLISH) =====
const manualContentHTML = `
    <h1>RBMK-1000 NUCLEAR POWER STATION</h1>
    <h2>TECHNICAL OPERATIONS MANUAL</h2>
    <p><strong>Classification:</strong> RESTRICTED</p>
    <p><strong>Document No:</strong> NPS-1994-047</p>
    <p><strong>Date:</strong> January 1994</p>

    <h2>TABLE OF CONTENTS</h2>
    <ol>
        <li>General Description</li>
        <li>Reactor Core Systems</li>
        <li>Cooling System Operations</li>
        <li>Power Generation</li>
        <li>Safety Systems</li>
        <li>Emergency Procedures</li>
        <li>Normal Operating Procedures</li>
        <li>Troubleshooting Guide</li>
    </ol>

    <h2>1. GENERAL DESCRIPTION</h2>
    <p>The RBMK-1000 (Reaktor Bolshoy Moshchnosti Kanalnyy) is a Soviet-designed nuclear power reactor. This manual covers the standard operating procedures for Station No. 4, located in the People's Socialist Republic.</p>
    
    <p><strong>Key Specifications:</strong></p>
    <table>
        <tr><th>Parameter</th><th>Value</th></tr>
        <tr><td>Thermal Power</td><td>3200 MW</td></tr>
        <tr><td>Electrical Output</td><td>1000 MW</td></tr>
        <tr><td>Coolant Type</td><td>Light Water</td></tr>
        <tr><td>Moderator</td><td>Graphite</td></tr>
        <tr><td>Fuel</td><td>UO₂ (2.0% enrichment)</td></tr>
        <tr><td>Operating Pressure</td><td>6.9 MPa</td></tr>
        <tr><td>Core Temperature</td><td>280-320°C</td></tr>
    </table>

    <h2>2. REACTOR CORE SYSTEMS</h2>
    
    <h3>2.1 Control Rods</h3>
    <p>The reactor employs 211 control rods for power regulation and emergency shutdown. Control rods absorb neutrons and regulate the fission rate.</p>
    
    <p><strong>Operating Positions:</strong></p>
    <ul>
        <li><strong>0-30%:</strong> High power operation (use with caution)</li>
        <li><strong>30-70%:</strong> Normal operating range</li>
        <li><strong>70-100%:</strong> Low power / shutdown condition</li>
    </ul>

    <div class="warning-box">
        <h3>⚠ WARNING</h3>
        <p>Rapid insertion of control rods can cause power oscillations. Always adjust gradually (5% increments maximum).</p>
    </div>

    <h3>2.2 Core Temperature Monitoring</h3>
    <p>Normal operating temperature: <strong>250-300°C</strong></p>
    <ul>
        <li><strong>Warning:</strong> > 300°C - Monitor closely</li>
        <li><strong>Danger:</strong> > 350°C - Take corrective action</li>
        <li><strong>Critical:</strong> > 400°C - Immediate shutdown required</li>
    </ul>

    <h2>3. COOLING SYSTEM OPERATIONS</h2>
    
    <h3>3.1 Main Coolant Pumps</h3>
    <p>The primary cooling circuit uses 8 main circulation pumps (MCPs). Normal operating speed: <strong>60-80%</strong></p>
    
    <h3>3.2 Emergency Core Cooling System (ECCS)</h3>
    <p>The ECCS can be activated manually or automatically when:</p>
    <ul>
        <li>Core temperature exceeds 350°C</li>
        <li>Pressure drops below 5.0 MPa</li>
        <li>Manual AZ-5 activation</li>
    </ul>

    <h3>3.3 Secondary Cooling Loop</h3>
    <p>Secondary loop parameters:</p>
    <table>
        <tr><th>Parameter</th><th>Normal Range</th></tr>
        <tr><td>Inlet Temperature</td><td>170-190°C</td></tr>
        <tr><td>Outlet Temperature</td><td>270-290°C</td></tr>
        <tr><td>Coolant Flow Rate</td><td>8000-9000 m³/h</td></tr>
        <tr><td>Pressurizer Level</td><td>50-70%</td></tr>
    </table>

    <h2>4. POWER GENERATION</h2>
    <p>Electrical output is generated by two turbo-generators rated at 500 MW each.</p>
    
    <h3>4.1 Grid Connection</h3>
    <p>Standard grid parameters:</p>
    <ul>
        <li><strong>Voltage:</strong> 15.75 kV (generator output)</li>
        <li><strong>Frequency:</strong> 50.0 Hz ± 0.2 Hz</li>
        <li><strong>Transmission:</strong> 330 kV / 750 kV lines</li>
    </ul>

    <h2>5. SAFETY SYSTEMS</h2>
    
    <h3>5.1 AZ-5 Emergency Protection</h3>
    <p>The AZ-5 (Аварийная Защита 5) button triggers complete reactor shutdown:</p>
    <ul>
        <li>All control rods fully inserted (100%)</li>
        <li>Emergency cooling activated</li>
        <li>Turbine generators disconnected from grid</li>
    </ul>

    <div class="warning-box">
        <h3>⚠ CRITICAL WARNING</h3>
        <p>AZ-5 activation is IRREVERSIBLE. The reactor cannot be restarted without a full reset procedure by authorized personnel only.</p>
        <p>Use ONLY in genuine emergency situations.</p>
    </div>

    <h3>5.2 Radiation Monitoring</h3>
    <table>
        <tr><th>Level</th><th>Reading</th><th>Action</th></tr>
        <tr><td>Normal</td><td>< 0.5 mSv/h</td><td>Continue operations</td></tr>
        <tr><td>Elevated</td><td>0.5 - 1.0 mSv/h</td><td>Investigate source</td></tr>
        <tr><td>Warning</td><td>1.0 - 5.0 mSv/h</td><td>Limit access</td></tr>
        <tr><td>Danger</td><td>> 5.0 mSv/h</td><td>Evacuate non-essential personnel</td></tr>
    </table>

    <h2>6. EMERGENCY PROCEDURES</h2>
    
    <h3>6.1 Loss of Coolant Accident (LOCA)</h3>
    <ol>
        <li>Activate ECCS immediately</li>
        <li>Insert control rods to 80%+</li>
        <li>Activate additional coolant pumps</li>
        <li>Monitor core temperature continuously</li>
        <li>If temperature exceeds 400°C, initiate AZ-5</li>
        <li>Notify Ministry of Energy</li>
    </ol>

    <h3>6.2 Power Excursion</h3>
    <ol>
        <li>Insert control rods immediately</li>
        <li>Reduce main pump speed if temperature rising</li>
        <li>Monitor pressure in primary circuit</li>
        <li>Prepare for possible AZ-5 activation</li>
    </ol>

    <h3>6.3 Station Blackout</h3>
    <ol>
        <li>Diesel generators should auto-start within 15 seconds</li>
        <li>Verify emergency cooling activation</li>
        <li>Control rods will auto-insert on power loss</li>
        <li>Monitor battery backup systems</li>
    </ol>

    <h2>7. NORMAL OPERATING PROCEDURES</h2>
    
    <h3>7.1 Reactor Startup</h3>
    <ol>
        <li>Verify all systems nominal</li>
        <li>Withdraw control rods gradually (5% per minute)</li>
        <li>Monitor neutron flux increase</li>
        <li>Bring reactor to critical state</li>
        <li>Stabilize at low power (10%)</li>
        <li>Gradually increase to target power</li>
        <li>Connect to grid when parameters stable</li>
    </ol>

    <h3>7.2 Routine Monitoring</h3>
    <p>Check the following every 30 minutes:</p>
    <ul>
        <li>Core temperature and pressure</li>
        <li>Coolant flow rates</li>
        <li>Radiation levels</li>
        <li>Generator output and frequency</li>
        <li>Grid connection status</li>
    </ul>

    <h3>7.3 Planned Shutdown</h3>
    <ol>
        <li>Disconnect from grid</li>
        <li>Reduce power gradually (10% per 5 minutes)</li>
        <li>Insert control rods to 100%</li>
        <li>Maintain cooling for 24 hours minimum</li>
        <li>Monitor decay heat</li>
    </ol>

    <h2>8. TROUBLESHOOTING GUIDE</h2>
    
    <table>
        <tr><th>Symptom</th><th>Possible Cause</th><th>Corrective Action</th></tr>
        <tr><td>High temperature</td><td>Insufficient cooling</td><td>Increase pump speed, activate ECCS</td></tr>
        <tr><td>High pressure</td><td>Overheating, blockage</td><td>Reduce power, check coolant flow</td></tr>
        <tr><td>Power oscillations</td><td>Control rod instability</td><td>Stabilize rod position</td></tr>
        <tr><td>High radiation</td><td>Fuel element damage</td><td>Reduce power, investigate</td></tr>
        <tr><td>Frequency deviation</td><td>Grid instability</td><td>Adjust turbine speed</td></tr>
        <tr><td>Low pressurizer level</td><td>Coolant leak</td><td>Check circuits, activate backup pumps</td></tr>
    </table>

    <div class="warning-box">
        <h3>⚠ REMEMBER</h3>
        <p>When in doubt, prioritize safety over power output. A shutdown reactor can be restarted. A destroyed reactor cannot.</p>
        <p><em>"The atom is a good servant but a bad master."</em></p>
    </div>

    <h2>APPENDIX A: EMERGENCY CONTACTS</h2>
    <table>
        <tr><th>Position</th><th>Extension</th></tr>
        <tr><td>Station Director</td><td>1001</td></tr>
        <tr><td>Chief Engineer</td><td>1002</td></tr>
        <tr><td>Safety Officer</td><td>1003</td></tr>
        <tr><td>Ministry of Energy</td><td>9000</td></tr>
        <tr><td>Emergency Services</td><td>9999</td></tr>
    </table>

    <p style="margin-top: 40px; text-align: center; color: #888;">
        <em>END OF MANUAL</em><br>
        <em>Document NPS-1994-047 Rev. 3</em><br>
        <em>Approved by Chief Engineer, Station No. 4</em>
    </p>
`;

// Export
if (typeof module !== 'undefined' && module.exports) {
    module.exports = manualContentHTML;
}
